gaopt = struct(...
    'Fitnessfunction', %% TODO
    'Featuresize', 1,
    'Targetsize', 1,
    'LB',[], ...
    'UB',[], ...
    'IntCon',[],...
    'Constraintfunction',@(x)(zeros(size(x,1),1)),...  % No constraint
    'PopulationSize',100,...
    'InitialPopulations',[],...
    'EliteCount',5,...
    'CrossRatio',0.8,...
    'MutationRate',0.2,...
    'MaxIteration',100,...
    'Verbose',false,...
    'TournamentSize',3,...
    'Maxstall',10,...
    'Tolerance',1e-6,...
    'Creationfunction',@gaCreation,...
    'Fitnessscalefunction',@gaFitnessScale,...
    'Distancefunction',@gaPareto,...
    'Selectfunction',@gaSelection,...
    'Mutationfunction',@gaMutation,...
    'Crossoverfunction',@gaCrossover,...
    'Hyperfunction',@(ga,gaopt)(0) ...     % To run after each 
    );

