psoopt = struct(...
    'Fitnessfunction', %% TODO
    'Featuresize', %% TODO
    'Targetsize', %% TODO
    %'NumOfParallel', %% TODO
    'LB',[], ...
    'UB',[], ...
    'IntCon',[],...
    'Constraintfunction',@(x)0,...  % No constraint
    'ParticleSize',100,...
    'InitialParticles',[],...
    'InitialVelocities',[],...
    %'InitialLocalBestParticles',[],...
    %'InitialGlobalBestParticles',[],...
    'C1',0.2,...
    'C2',0.2,...
    'w',1.0,...
    'MutationRate',0.2,...
    %'StallIterationLimit',50,...
    %'StallTimeLimit',Inf,...
    %'ToleranceFitness',1e-6,...
    %'Timelimit',Inf,...
    'MaxIteration',100,...
    'Verbose',false,...
    'Creationfunction',@psoCreation,...
    'Fitnessscalefunction',@psoFitnessScale,...
    'Distancefunction',@psoPareto,...
    'Mutationfunction',@psoMutation,...
    'Hyperfunction',@psoLog     % To run after each 
    );

